"""Top-level package for funart_apis."""

# 从各个节点组导入并合并
from .nodes_image_edit import NODE_CLASS_MAPPINGS as IMAGE_EDIT_NODE_CLASS_MAPPINGS
from .nodes_image_edit import NODE_DISPLAY_NAME_MAPPINGS as IMAGE_EDIT_NODE_DISPLAY_NAME_MAPPINGS
from .nodes_fc import NODE_CLASS_MAPPINGS as FC_NODE_CLASS_MAPPINGS
from .nodes_fc import NODE_DISPLAY_NAME_MAPPINGS as FC_NODE_DISPLAY_NAME_MAPPINGS

# 合并所有节点映射
NODE_CLASS_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS = {}

NODE_CLASS_MAPPINGS.update(IMAGE_EDIT_NODE_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(IMAGE_EDIT_NODE_DISPLAY_NAME_MAPPINGS)

NODE_CLASS_MAPPINGS.update(FC_NODE_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(FC_NODE_DISPLAY_NAME_MAPPINGS)

__all__ = [
    "NODE_CLASS_MAPPINGS",
    "NODE_DISPLAY_NAME_MAPPINGS",
]

__author__ = """zijian"""
__email__ = "qiucheng.wzj@alibaba-inc.com"
__version__ = "0.0.1"
