"""
FunArt APIs for ComfyUI
包含多个功能集合的节点组
"""

# 导入各个节点组
from .wan_nodes import NODE_CLASS_MAPPINGS as WAN_NODE_CLASS_MAPPINGS
from .wan_nodes import NODE_DISPLAY_NAME_MAPPINGS as WAN_NODE_DISPLAY_NAME_MAPPINGS
from .fc_nodes import NODE_CLASS_MAPPINGS as FC_NODE_CLASS_MAPPINGS
from .fc_nodes import NODE_DISPLAY_NAME_MAPPINGS as FC_NODE_DISPLAY_NAME_MAPPINGS

# 合并所有节点映射
NODE_CLASS_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS = {}

# 注册 Wan 节点组
NODE_CLASS_MAPPINGS.update(WAN_NODE_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(WAN_NODE_DISPLAY_NAME_MAPPINGS)

# 注册 FC 节点组
NODE_CLASS_MAPPINGS.update(FC_NODE_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(FC_NODE_DISPLAY_NAME_MAPPINGS)

# 导出
__all__ = [
    "NODE_CLASS_MAPPINGS",
    "NODE_DISPLAY_NAME_MAPPINGS",
]
